/*
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package pdnsapi

type ModelError struct {

	// A human readable error message
	Error_ string `json:"error,omitempty"`

	// Optional array of multiple errors encountered during processing
	Errors []string `json:"errors,omitempty"`
}
