// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Server server
// swagger:model Server

type Server struct {

	// The API endpoint for this server’s configuration
	ConfigURL string `json:"config_url,omitempty"`

	// “recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server
	DaemonType string `json:"daemon_type,omitempty"`

	// The id of the server, “localhost”
	ID string `json:"id,omitempty"`

	// Set to “Server”
	Type string `json:"type,omitempty"`

	// The API endpoint for this server
	URL string `json:"url,omitempty"`

	// The version of the server software
	Version string `json:"version,omitempty"`

	// The API endpoint for this server’s zones
	ZonesURL string `json:"zones_url,omitempty"`
}

/* polymorph Server config_url false */

/* polymorph Server daemon_type false */

/* polymorph Server id false */

/* polymorph Server type false */

/* polymorph Server url false */

/* polymorph Server version false */

/* polymorph Server zones_url false */

// Validate validates this server
func (m *Server) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Server) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Server) UnmarshalBinary(b []byte) error {
	var res Server
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
